In [5]:
import numpy as np
import cv2

x = np.array([[1,1,1,0,0],
              [0,1,1,1,0],
              [0,0,1,1,1],
              [0,1,1,1,0],
              [0,1,1,0,0]], dtype=float)
kernel = np.array([[1,1,1],
                   [1,1,1],
                   [1,1,1]])
y = cv2.filter2D(x, -1, kernel, borderType=cv2.BORDER_CONSTANT)
print(y)

[[3. 5. 5. 3. 1.]
 [3. 6. 7. 6. 3.]
 [2. 5. 8. 7. 4.]
 [2. 5. 7. 6. 3.]
 [2. 4. 5. 3. 1.]]
